export const categoryMap: Record<string, string> = {
  beauty: 'красота',
  fragrances: 'парфюмерия',
  furniture: 'мебель',
  groceries: 'бакалея',
  'home-decoration': 'декор для дома',
  'kitchen-accessories': 'аксессуары для кухни',
  laptops: 'ноутбуки',
  'mens-shirts': 'мужские рубашки',
  'mens-shoes': 'мужская обувь',
  'mens-watches': 'мужские часы',
  'mobile-accessories': 'аксессуары для мобильных',
  motorcycle: 'мотоциклы',
  'skin-care': 'уход за кожей',
  smartphones: 'смартфоны',
  'sports-accessories': 'спортивные аксессуары',
  sunglasses: 'солнцезащитные очки',
  tablets: 'планшеты',
  tops: 'топы',
  vehicle: 'транспорт',
  'womens-bags': 'женские сумки',
  'womens-dresses': 'женские платья',
  'womens-jewellery': 'женские украшения',
  'womens-shoes': 'женская обувь',
  'womens-watches': 'женские часы',
};
